# @package _global_

defaults:
  # enable color logging
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

  # searching hyperparameter with Optuna
  - override hydra/sweeper: optuna
  # for multiprocessing
  - override hydra/launcher: joblib

x: ???

hydra:
    sweeper:
      study_name: quadratic_function
      direction: minimize
      n_trials: 1000
      n_jobs: 16

    launcher:
      n_jobs: 16


    run:
        dir: logs/runs/${now:%Y-%m-%d}/${now:%H:%M:%S}/${hydra.job.override_dirname}
    sweep:
        dir: logs/multiruns/${now:%Y-%m-%d}/${now:%H:%M:%S}/
        subdir: experiments/${hydra.job.override_dirname}
    job:
      config:
        # configuration for the ${hydra.job.override_dirname} runtime variable
        override_dirname:
          kv_sep: '='
          item_sep: '/'